-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 09:52:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetVelo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetVelo` ;

-- -----------------------------------------------------
-- Schema projetVelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetVelo` DEFAULT CHARACTER SET utf8 ;
USE `projetVelo` ;

-- -----------------------------------------------------
-- Table `projetVelo`.`Rents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetVelo`.`Rents` ;

CREATE TABLE IF NOT EXISTS `projetVelo`.`Rents` (
  `idRents` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idRents`),
  UNIQUE INDEX `idRents_UNIQUE` (`idRents` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetVelo`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetVelo`.`Customers` ;

CREATE TABLE IF NOT EXISTS `projetVelo`.`Customers` (
  `idCustomers` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCustomers`),
  UNIQUE INDEX `idCustomers_UNIQUE` (`idCustomers` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetVelo`.`typesOfBikes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetVelo`.`typesOfBikes` ;

CREATE TABLE IF NOT EXISTS `projetVelo`.`typesOfBikes` (
  `idtypesOfBikes` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idtypesOfBikes`),
  UNIQUE INDEX `idtypesOfBikes_UNIQUE` (`idtypesOfBikes` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetVelo`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetVelo`.`Address` ;

CREATE TABLE IF NOT EXISTS `projetVelo`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idAddress`),
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetVelo`.`ZipCodesAndCities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetVelo`.`ZipCodesAndCities` ;

CREATE TABLE IF NOT EXISTS `projetVelo`.`ZipCodesAndCities` (
  `idZipCodesAndCities` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idZipCodesAndCities`),
  UNIQUE INDEX `idZipCodesAndCities_UNIQUE` (`idZipCodesAndCities` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
