-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 18:18:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lacrImmoBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lacrImmoBD` ;

-- -----------------------------------------------------
-- Schema lacrImmoBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lacrImmoBD` DEFAULT CHARACTER SET utf8 ;
USE `lacrImmoBD` ;

-- -----------------------------------------------------
-- Table `lacrImmoBD`.`PropertiesTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`PropertiesTypes` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`PropertiesTypes` (
  `idPropertiesTypes` INT NOT NULL AUTO_INCREMENT,
  `propertieType` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPropertiesTypes`),
  UNIQUE INDEX `idPropertiesTypes_UNIQUE` (`idPropertiesTypes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`TransactionTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`TransactionTypes` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`TransactionTypes` (
  `idTransactionTypes` INT NOT NULL AUTO_INCREMENT,
  `transactionType` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTransactionTypes`),
  UNIQUE INDEX `idTransactionTypes_UNIQUE` (`idTransactionTypes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`TotalRooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`TotalRooms` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`TotalRooms` (
  `idTotalRooms` INT NOT NULL AUTO_INCREMENT,
  `totalRooms` INT NOT NULL,
  PRIMARY KEY (`idTotalRooms`),
  UNIQUE INDEX `idTotalRooms_UNIQUE` (`idTotalRooms` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`CommissionRates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`CommissionRates` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`CommissionRates` (
  `idCommissionRates` INT NOT NULL AUTO_INCREMENT,
  `commissionRate` FLOAT NOT NULL,
  PRIMARY KEY (`idCommissionRates`),
  UNIQUE INDEX `idCommissionRates_UNIQUE` (`idCommissionRates` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`Regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`Regions` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`Regions` (
  `idRegions` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRegions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`ZipCodesAndCities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`ZipCodesAndCities` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`ZipCodesAndCities` (
  `idZipCodesAndCities` INT NOT NULL AUTO_INCREMENT,
  `zipCode` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `Regions_idRegions` INT NOT NULL,
  PRIMARY KEY (`idZipCodesAndCities`, `Regions_idRegions`),
  UNIQUE INDEX `idZipCodesAndCities_UNIQUE` (`idZipCodesAndCities` ASC),
  INDEX `fk_ZipCodesAndCities_Regions1_idx` (`Regions_idRegions` ASC),
  CONSTRAINT `fk_ZipCodesAndCities_Regions1`
    FOREIGN KEY (`Regions_idRegions`)
    REFERENCES `lacrImmoBD`.`Regions` (`idRegions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`Address` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `streetNumber` INT NULL,
  `complStreetNumber` VARCHAR(5) NULL,
  `streetName` VARCHAR(45) NULL,
  `complStreetname` VARCHAR(45) NULL,
  `ZipCodesAndCities_idZipCodesAndCities` INT NOT NULL,
  `ZipCodesAndCities_Regions_idRegions` INT NOT NULL,
  PRIMARY KEY (`idAddress`, `ZipCodesAndCities_idZipCodesAndCities`, `ZipCodesAndCities_Regions_idRegions`),
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC),
  INDEX `fk_Address_ZipCodesAndCities1_idx` (`ZipCodesAndCities_idZipCodesAndCities` ASC, `ZipCodesAndCities_Regions_idRegions` ASC),
  CONSTRAINT `fk_Address_ZipCodesAndCities1`
    FOREIGN KEY (`ZipCodesAndCities_idZipCodesAndCities` , `ZipCodesAndCities_Regions_idRegions`)
    REFERENCES `lacrImmoBD`.`ZipCodesAndCities` (`idZipCodesAndCities` , `Regions_idRegions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`Properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`Properties` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`Properties` (
  `idOffers` INT NOT NULL AUTO_INCREMENT,
  `propertyTypeDescription` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `additionnalCharges` VARCHAR(3) NOT NULL,
  `garden` VARCHAR(3) NOT NULL,
  `garage` VARCHAR(3) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `photoName` VARCHAR(45) NOT NULL,
  `PropertiesTypes_idPropertiesTypes` INT NOT NULL,
  `TransactionTypes_idTransactionTypes` INT NOT NULL,
  `TotalRooms_idTotalRooms` INT NOT NULL,
  `CommissionRates_idCommissionRates` INT NOT NULL,
  `Address_idAddress` INT NOT NULL,
  `Address_ZipCodesAndCities_idZipCodesAndCities` INT NOT NULL,
  `Address_ZipCodesAndCities_Regions_idRegions` INT NOT NULL,
  PRIMARY KEY (`idOffers`, `PropertiesTypes_idPropertiesTypes`, `TransactionTypes_idTransactionTypes`, `TotalRooms_idTotalRooms`, `CommissionRates_idCommissionRates`, `Address_idAddress`, `Address_ZipCodesAndCities_idZipCodesAndCities`, `Address_ZipCodesAndCities_Regions_idRegions`),
  UNIQUE INDEX `idOffers_UNIQUE` (`idOffers` ASC),
  INDEX `fk_Properties_PropertiesTypes1_idx` (`PropertiesTypes_idPropertiesTypes` ASC),
  INDEX `fk_Properties_TransactionTypes1_idx` (`TransactionTypes_idTransactionTypes` ASC),
  INDEX `fk_Properties_TotalRooms1_idx` (`TotalRooms_idTotalRooms` ASC),
  INDEX `fk_Properties_CommissionRates1_idx` (`CommissionRates_idCommissionRates` ASC),
  INDEX `fk_Properties_Address1_idx` (`Address_idAddress` ASC, `Address_ZipCodesAndCities_idZipCodesAndCities` ASC, `Address_ZipCodesAndCities_Regions_idRegions` ASC),
  CONSTRAINT `fk_Properties_PropertiesTypes1`
    FOREIGN KEY (`PropertiesTypes_idPropertiesTypes`)
    REFERENCES `lacrImmoBD`.`PropertiesTypes` (`idPropertiesTypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Properties_TransactionTypes1`
    FOREIGN KEY (`TransactionTypes_idTransactionTypes`)
    REFERENCES `lacrImmoBD`.`TransactionTypes` (`idTransactionTypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Properties_TotalRooms1`
    FOREIGN KEY (`TotalRooms_idTotalRooms`)
    REFERENCES `lacrImmoBD`.`TotalRooms` (`idTotalRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Properties_CommissionRates1`
    FOREIGN KEY (`CommissionRates_idCommissionRates`)
    REFERENCES `lacrImmoBD`.`CommissionRates` (`idCommissionRates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Properties_Address1`
    FOREIGN KEY (`Address_idAddress` , `Address_ZipCodesAndCities_idZipCodesAndCities` , `Address_ZipCodesAndCities_Regions_idRegions`)
    REFERENCES `lacrImmoBD`.`Address` (`idAddress` , `ZipCodesAndCities_idZipCodesAndCities` , `ZipCodesAndCities_Regions_idRegions`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`Contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`Contacts` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`Contacts` (
  `idContacts` INT NOT NULL AUTO_INCREMENT,
  `object` VARCHAR(45) NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idContacts`),
  UNIQUE INDEX `idContacts_UNIQUE` (`idContacts` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`UsersType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`UsersType` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`UsersType` (
  `idUsersType` INT NOT NULL AUTO_INCREMENT,
  `userType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsersType`),
  UNIQUE INDEX `idUsersType_UNIQUE` (`idUsersType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacrImmoBD`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lacrImmoBD`.`Users` ;

CREATE TABLE IF NOT EXISTS `lacrImmoBD`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `Contacts_idContacts` INT NOT NULL,
  `UsersType_idUsersType` INT NOT NULL,
  `Address_idAddress` INT NOT NULL,
  PRIMARY KEY (`idUsers`, `Contacts_idContacts`, `UsersType_idUsersType`, `Address_idAddress`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC),
  INDEX `fk_Users_Contacts_idx` (`Contacts_idContacts` ASC),
  INDEX `fk_Users_UsersType1_idx` (`UsersType_idUsersType` ASC),
  INDEX `fk_Users_Address1_idx` (`Address_idAddress` ASC),
  CONSTRAINT `fk_Users_Contacts`
    FOREIGN KEY (`Contacts_idContacts`)
    REFERENCES `lacrImmoBD`.`Contacts` (`idContacts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_UsersType1`
    FOREIGN KEY (`UsersType_idUsersType`)
    REFERENCES `lacrImmoBD`.`UsersType` (`idUsersType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `lacrImmoBD`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`PropertiesTypes`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`PropertiesTypes` (`idPropertiesTypes`, `propertieType`) VALUES (1, 'Maison');
INSERT INTO `lacrImmoBD`.`PropertiesTypes` (`idPropertiesTypes`, `propertieType`) VALUES (2, 'Appartement');

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`TransactionTypes`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`TransactionTypes` (`idTransactionTypes`, `transactionType`) VALUES (1, 'Achat');
INSERT INTO `lacrImmoBD`.`TransactionTypes` (`idTransactionTypes`, `transactionType`) VALUES (2, 'Location');

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`TotalRooms`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (1, 1);
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (2, 2);
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (3, 3);
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (4, 4);
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (5, 5);
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (6, 6);
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (7, 7);
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (8, 8);
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (9, 9);
INSERT INTO `lacrImmoBD`.`TotalRooms` (`idTotalRooms`, `totalRooms`) VALUES (10, 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`CommissionRates`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`CommissionRates` (`idCommissionRates`, `commissionRate`) VALUES (1, 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`Regions`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`Regions` (`idRegions`, `region`) VALUES (1, 'Hauts-de-France');

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`ZipCodesAndCities`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`ZipCodesAndCities` (`idZipCodesAndCities`, `zipCode`, `city`, `Regions_idRegions`) VALUES (1, '62800', 'Liévin', 1);
INSERT INTO `lacrImmoBD`.`ZipCodesAndCities` (`idZipCodesAndCities`, `zipCode`, `city`, `Regions_idRegions`) VALUES (2, '59170', 'Roubaix', 1);
INSERT INTO `lacrImmoBD`.`ZipCodesAndCities` (`idZipCodesAndCities`, `zipCode`, `city`, `Regions_idRegions`) VALUES (3, '59200', 'Tourcoing', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`Address`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`Address` (`idAddress`, `streetNumber`, `complStreetNumber`, `streetName`, `complStreetname`, `ZipCodesAndCities_idZipCodesAndCities`, `ZipCodesAndCities_Regions_idRegions`) VALUES (1, 41, NULL, 'Rue Henri Martin', NULL, 1, 1);
INSERT INTO `lacrImmoBD`.`Address` (`idAddress`, `streetNumber`, `complStreetNumber`, `streetName`, `complStreetname`, `ZipCodesAndCities_idZipCodesAndCities`, `ZipCodesAndCities_Regions_idRegions`) VALUES (2, NULL, NULL, 'Petite maison dans la Prairie', NULL, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`Properties`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`Properties` (`idOffers`, `propertyTypeDescription`, `description`, `additionnalCharges`, `garden`, `garage`, `price`, `photoName`, `PropertiesTypes_idPropertiesTypes`, `TransactionTypes_idTransactionTypes`, `TotalRooms_idTotalRooms`, `CommissionRates_idCommissionRates`, `Address_idAddress`, `Address_ZipCodesAndCities_idZipCodesAndCities`, `Address_ZipCodesAndCities_Regions_idRegions`) VALUES (1, 'Grande maison pavillonaire', 'Grande maison pavillonaire à proximité du centre et des écoles. Salon séjour de 18.5m², cuisine de 10.41m², salle de bains avec vasque et baignoire de 5.6... ', 'Oui', 'Oui', 'Oui', 250000, DEFAULT, 1, 1, 5, 1, 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`Contacts`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`Contacts` (`idContacts`, `object`, `message`) VALUES (1, 'Votre annonce n° 1', 'Je suis très intéressé par votre maison');

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`UsersType`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`UsersType` (`idUsersType`, `userType`) VALUES (1, 'Client');
INSERT INTO `lacrImmoBD`.`UsersType` (`idUsersType`, `userType`) VALUES (2, 'Commercial');

COMMIT;


-- -----------------------------------------------------
-- Data for table `lacrImmoBD`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `lacrImmoBD`;
INSERT INTO `lacrImmoBD`.`Users` (`idUsers`, `lastname`, `firstname`, `email`, `phoneNumber`, `Contacts_idContacts`, `UsersType_idUsersType`, `Address_idAddress`) VALUES (1, 'Ingalls', 'Charles', 'lapetitemaison@gmail.com', '0300000000', 1, 1, 2);

COMMIT;

