-- MySQL Script generated by MySQL Workbench
-- Wed Jan 15 15:39:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema formateursSalles
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `formateursSalles` ;

-- -----------------------------------------------------
-- Schema formateursSalles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formateursSalles` DEFAULT CHARACTER SET utf8 ;
USE `formateursSalles` ;

-- -----------------------------------------------------
-- Table `formateursSalles`.`Specialities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`Specialities` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`Specialities` (
  `idSpeciality` INT NOT NULL AUTO_INCREMENT,
  `SpecialityType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSpeciality`),
  UNIQUE INDEX `idSpecialities_UNIQUE` (`idSpeciality` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`SkillsType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`SkillsType` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`SkillsType` (
  `idSkillsType` INT NOT NULL AUTO_INCREMENT,
  `skillName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSkillsType`),
  UNIQUE INDEX `idSkillsType_UNIQUE` (`idSkillsType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`Skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`Skills` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`Skills` (
  `idSkills` INT NOT NULL AUTO_INCREMENT,
  `SkillsType_idSkillsType` INT NOT NULL,
  PRIMARY KEY (`idSkills`, `SkillsType_idSkillsType`),
  UNIQUE INDEX `idSkills_UNIQUE` (`idSkills` ASC),
  INDEX `fk_Skills_SkillsType1_idx` (`SkillsType_idSkillsType` ASC),
  CONSTRAINT `fk_Skills_SkillsType1`
    FOREIGN KEY (`SkillsType_idSkillsType`)
    REFERENCES `formateursSalles`.`SkillsType` (`idSkillsType`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`contractTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`contractTypes` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`contractTypes` (
  `idcontractTypes` INT NOT NULL AUTO_INCREMENT,
  `contractTypesName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idcontractTypes`),
  UNIQUE INDEX `idcontractTypes_UNIQUE` (`idcontractTypes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`ZipCodeCities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`ZipCodeCities` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`ZipCodeCities` (
  `idZipCodeCities` INT NOT NULL AUTO_INCREMENT,
  `zipCodeNumber` VARCHAR(10) NOT NULL,
  `ZipCodeCity` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idZipCodeCities`),
  UNIQUE INDEX `idZipCodeCities_UNIQUE` (`idZipCodeCities` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`Address` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `streetNumber` INT NULL,
  `complStreetNumber` VARCHAR(45) NULL,
  `streetName` VARCHAR(45) NOT NULL,
  `ZipCodeCities_idZipCodeCities` INT NOT NULL,
  PRIMARY KEY (`idAddress`, `ZipCodeCities_idZipCodeCities`),
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC),
  INDEX `fk_Address_ZipCodeCities1_idx` (`ZipCodeCities_idZipCodeCities` ASC),
  CONSTRAINT `fk_Address_ZipCodeCities1`
    FOREIGN KEY (`ZipCodeCities_idZipCodeCities`)
    REFERENCES `formateursSalles`.`ZipCodeCities` (`idZipCodeCities`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`Formateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`Formateurs` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`Formateurs` (
  `idFormateurs` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `experience` VARCHAR(45) NOT NULL,
  `indemnities` DECIMAL(10,2) NOT NULL,
  `active` TINYINT NULL,
  `status` VARCHAR(20) NOT NULL,
  `availability` TINYINT NOT NULL,
  `Salles_idSalles` INT NOT NULL,
  `Specialities_idSpeciality` INT NOT NULL,
  `Skills_idSkills` INT NOT NULL,
  `contractTypes_idcontractTypes` INT NOT NULL,
  `Address_idAddress` INT NOT NULL,
  PRIMARY KEY (`idFormateurs`, `Salles_idSalles`, `Specialities_idSpeciality`, `Skills_idSkills`, `contractTypes_idcontractTypes`, `Address_idAddress`),
  UNIQUE INDEX `idFormateurs_UNIQUE` (`idFormateurs` ASC),
  INDEX `fk_Formateurs_Specialities1_idx` (`Specialities_idSpeciality` ASC),
  INDEX `fk_Formateurs_Skills1_idx` (`Skills_idSkills` ASC),
  INDEX `fk_Formateurs_contractTypes1_idx` (`contractTypes_idcontractTypes` ASC),
  INDEX `fk_Formateurs_Address1_idx` (`Address_idAddress` ASC),
  CONSTRAINT `fk_Formateurs_Specialities1`
    FOREIGN KEY (`Specialities_idSpeciality`)
    REFERENCES `formateursSalles`.`Specialities` (`idSpeciality`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Formateurs_Skills1`
    FOREIGN KEY (`Skills_idSkills`)
    REFERENCES `formateursSalles`.`Skills` (`idSkills`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Formateurs_contractTypes1`
    FOREIGN KEY (`contractTypes_idcontractTypes`)
    REFERENCES `formateursSalles`.`contractTypes` (`idcontractTypes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Formateurs_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `formateursSalles`.`Address` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`Equipments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`Equipments` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`Equipments` (
  `idEquipments` INT NOT NULL AUTO_INCREMENT,
  `equipmentName` VARCHAR(45) NOT NULL,
  `equipmentNumber` VARCHAR(20) NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`idEquipments`),
  UNIQUE INDEX `idEquipments_UNIQUE` (`idEquipments` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`RoomTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`RoomTypes` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`RoomTypes` (
  `idRoomTypes` INT NOT NULL AUTO_INCREMENT,
  `roomType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoomTypes`),
  UNIQUE INDEX `idRoomTypes_UNIQUE` (`idRoomTypes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`Salles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`Salles` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`Salles` (
  `idSalles` INT NOT NULL AUTO_INCREMENT,
  `classroomNumber` VARCHAR(45) NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  `disabledAccessibility` TINYINT NOT NULL,
  `active` TINYINT NOT NULL,
  `Equipments_idEquipments` INT NOT NULL,
  `RoomTypes_idRoomTypes` INT NOT NULL,
  PRIMARY KEY (`idSalles`, `Equipments_idEquipments`, `RoomTypes_idRoomTypes`),
  UNIQUE INDEX `idSalles_UNIQUE` (`idSalles` ASC),
  INDEX `fk_Salles_Equipments1_idx` (`Equipments_idEquipments` ASC),
  INDEX `fk_Salles_RoomTypes1_idx` (`RoomTypes_idRoomTypes` ASC),
  CONSTRAINT `fk_Salles_Equipments1`
    FOREIGN KEY (`Equipments_idEquipments`)
    REFERENCES `formateursSalles`.`Equipments` (`idEquipments`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Salles_RoomTypes1`
    FOREIGN KEY (`RoomTypes_idRoomTypes`)
    REFERENCES `formateursSalles`.`RoomTypes` (`idRoomTypes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`TrainingCenters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`TrainingCenters` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`TrainingCenters` (
  `idTrainingCenters` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Address_idAddress` INT NOT NULL,
  `Salles_idSalles` INT NOT NULL,
  `Salles_Equipments_idEquipments` INT NOT NULL,
  `Salles_RoomTypes_idRoomTypes` INT NOT NULL,
  PRIMARY KEY (`idTrainingCenters`, `Address_idAddress`, `Salles_idSalles`, `Salles_Equipments_idEquipments`, `Salles_RoomTypes_idRoomTypes`),
  UNIQUE INDEX `idTrainingCenters_UNIQUE` (`idTrainingCenters` ASC),
  INDEX `fk_TrainingCenters_Address1_idx` (`Address_idAddress` ASC),
  INDEX `fk_TrainingCenters_Salles1_idx` (`Salles_idSalles` ASC, `Salles_Equipments_idEquipments` ASC, `Salles_RoomTypes_idRoomTypes` ASC),
  CONSTRAINT `fk_TrainingCenters_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `formateursSalles`.`Address` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TrainingCenters_Salles1`
    FOREIGN KEY (`Salles_idSalles` , `Salles_Equipments_idEquipments` , `Salles_RoomTypes_idRoomTypes`)
    REFERENCES `formateursSalles`.`Salles` (`idSalles` , `Equipments_idEquipments` , `RoomTypes_idRoomTypes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`typeOfTravels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`typeOfTravels` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`typeOfTravels` (
  `idtypeOfTravels` INT NOT NULL AUTO_INCREMENT,
  `travelNameType` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idtypeOfTravels`),
  UNIQUE INDEX `idtypeOfTravels_UNIQUE` (`idtypeOfTravels` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`Formateurs_has_typeOfTravels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`Formateurs_has_typeOfTravels` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`Formateurs_has_typeOfTravels` (
  `Formateurs_idFormateurs` INT NOT NULL,
  `Formateurs_Salles_idSalles` INT NOT NULL,
  `Formateurs_Specialities_idSpeciality` INT NOT NULL,
  `Formateurs_Skills_idSkills` INT NOT NULL,
  `typeOfTravels_idtypeOfTravels` INT NOT NULL,
  PRIMARY KEY (`Formateurs_idFormateurs`, `Formateurs_Salles_idSalles`, `Formateurs_Specialities_idSpeciality`, `Formateurs_Skills_idSkills`, `typeOfTravels_idtypeOfTravels`),
  INDEX `fk_Formateurs_has_typeOfTravels_typeOfTravels1_idx` (`typeOfTravels_idtypeOfTravels` ASC),
  INDEX `fk_Formateurs_has_typeOfTravels_Formateurs1_idx` (`Formateurs_idFormateurs` ASC, `Formateurs_Salles_idSalles` ASC, `Formateurs_Specialities_idSpeciality` ASC, `Formateurs_Skills_idSkills` ASC),
  CONSTRAINT `fk_Formateurs_has_typeOfTravels_Formateurs1`
    FOREIGN KEY (`Formateurs_idFormateurs` , `Formateurs_Salles_idSalles` , `Formateurs_Specialities_idSpeciality` , `Formateurs_Skills_idSkills`)
    REFERENCES `formateursSalles`.`Formateurs` (`idFormateurs` , `Salles_idSalles` , `Specialities_idSpeciality` , `Skills_idSkills`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Formateurs_has_typeOfTravels_typeOfTravels1`
    FOREIGN KEY (`typeOfTravels_idtypeOfTravels`)
    REFERENCES `formateursSalles`.`typeOfTravels` (`idtypeOfTravels`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
