-- MySQL Script generated by MySQL Workbench
-- Tue Jan 14 18:24:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EssaiTable
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EssaiTable` ;

-- -----------------------------------------------------
-- Schema EssaiTable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EssaiTable` DEFAULT CHARACTER SET utf8 ;
USE `EssaiTable` ;

-- -----------------------------------------------------
-- Table `EssaiTable`.`Formateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EssaiTable`.`Formateurs` ;

CREATE TABLE IF NOT EXISTS `EssaiTable`.`Formateurs` (
  `idFormateur` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `speciality` VARCHAR(45) NOT NULL,
  `trainingCenter` VARCHAR(45) NOT NULL,
  `contractType` VARCHAR(10) NOT NULL,
  `birthdate` DATE NOT NULL,
  `skills` VARCHAR(45) NOT NULL,
  `experience` VARCHAR(45) NOT NULL,
  `indemnities` DECIMAL(10,2) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `availability` TINYINT NULL,
  `typeOfTravel` VARCHAR(45) NOT NULL,
  `active` TINYINT NULL,
  `statut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFormateur`),
  UNIQUE INDEX `idusers_UNIQUE` (`idFormateur` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
