-- MySQL Script generated by MySQL Workbench
-- Wed Jan 15 08:03:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema formateursSalles
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `formateursSalles` ;

-- -----------------------------------------------------
-- Schema formateursSalles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formateursSalles` DEFAULT CHARACTER SET utf8 ;
USE `formateursSalles` ;

-- -----------------------------------------------------
-- Table `formateursSalles`.`Formateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`Formateurs` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`Formateurs` (
  `idFormateurs` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `speciality` VARCHAR(45) NOT NULL,
  `trainingCenter` VARCHAR(45) NOT NULL,
  `contractType` VARCHAR(15) NOT NULL,
  `birthdate` DATE NOT NULL,
  `skills` VARCHAR(45) NOT NULL,
  `experience` VARCHAR(45) NOT NULL,
  `indemnities` DECIMAL(10,2) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `avaibility` TINYINT NULL,
  `typeOfTravel` VARCHAR(45) NOT NULL,
  `active` TINYINT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idFormateurs`),
  UNIQUE INDEX `idFormateurs_UNIQUE` (`idFormateurs` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formateursSalles`.`Specialities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formateursSalles`.`Specialities` ;

CREATE TABLE IF NOT EXISTS `formateursSalles`.`Specialities` (
  `idSpeciality` INT NOT NULL AUTO_INCREMENT,
  `SpecialityType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSpeciality`),
  UNIQUE INDEX `idSpecialities_UNIQUE` (`idSpeciality` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
